global:
  scrape_interval: 12s
scrape_configs:
 - job_name: prometheus
   static_configs:
    - targets:
       - localhost:9090
 - job_name: Result
   static_configs:
    - targets:
       - localhost:8000
 - job_name: FLASK_API
   static_configs:
    - targets:
       - localhost:5000