version: "2"

services:
  api:
    restart: always
    build: ./app
    ports:
      - 5000
    environment:
      - SERVICE_PORTS=5000
  client:
    restart: always
    build: ./result_exporter
    ports:
      - 8000

  loadbalancer:
    image: 'dockercloud/haproxy:latest'
    links:
      - api
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - BALANCE=leastconn
    ports:
      - 80:80